name = "bolt-ai"
main = "worker.js"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./build/client"

[build]
command = "npm run build && npx esbuild worker.ts --bundle --outfile=worker.js --format=esm --platform=neutral --target=esnext --external:__STATIC_CONTENT_MANIFEST"

[vars]
NODE_ENV = "production"

[dev]
port = 8788
